import { FurnitureItem, DesignStyle } from "./types";

// A curated catalog of furniture items for vacation rental design.
// In production this would connect to Spoak, Wayfair APIs, etc.

let _id = 0;
function item(
  p: Omit<FurnitureItem, "id"> & { id?: string }
): FurnitureItem {
  return { ...p, id: p.id ?? `cat-${++_id}` };
}

export const CATALOG: FurnitureItem[] = [
  // ══════════════════════════════════════
  //  BEDS & MATTRESSES
  // ══════════════════════════════════════
  item({
    name: "Queen/Queen Bunk Bed Frame",
    category: "beds-mattresses",
    subcategory: "Bunk Beds",
    widthIn: 65,
    depthIn: 84,
    heightIn: 72,
    price: 1299,
    vendor: "Adult Bunk Beds",
    vendorUrl: "https://adultbunkbeds.com",
    imageUrl: "",
    color: "Natural Wood",
    material: "Solid Pine",
    style: "rustic",
  }),
  item({
    name: "Queen/Queen Metal Bunk Frame",
    category: "beds-mattresses",
    subcategory: "Bunk Beds",
    widthIn: 64,
    depthIn: 82,
    heightIn: 74,
    price: 899,
    vendor: "Francis Lofts & Bunks",
    vendorUrl: "https://francisloftsbunks.com",
    imageUrl: "",
    color: "Matte Black",
    material: "Steel",
    style: "industrial",
  }),
  item({
    name: "Twin/Twin Bunk Bed",
    category: "beds-mattresses",
    subcategory: "Bunk Beds",
    widthIn: 42,
    depthIn: 78,
    heightIn: 65,
    price: 449,
    vendor: "Wayfair",
    vendorUrl: "https://wayfair.com",
    imageUrl: "",
    color: "White",
    material: "Solid Wood",
    style: "coastal",
  }),
  item({
    name: "Twin/Full Bunk Bed",
    category: "beds-mattresses",
    subcategory: "Bunk Beds",
    widthIn: 58,
    depthIn: 78,
    heightIn: 65,
    price: 549,
    vendor: "Wayfair",
    vendorUrl: "https://wayfair.com",
    imageUrl: "",
    color: "Gray",
    material: "Metal & Wood",
    style: "contemporary",
  }),
  item({
    name: "King Platform Bed Frame",
    category: "beds-mattresses",
    subcategory: "Bed Frames",
    widthIn: 80,
    depthIn: 84,
    heightIn: 42,
    price: 799,
    vendor: "Article",
    vendorUrl: "https://article.com",
    imageUrl: "",
    color: "Walnut",
    material: "Solid Walnut",
    style: "mid-century",
  }),
  item({
    name: "Queen Upholstered Bed",
    category: "beds-mattresses",
    subcategory: "Bed Frames",
    widthIn: 66,
    depthIn: 88,
    heightIn: 50,
    price: 649,
    vendor: "West Elm",
    vendorUrl: "https://westelm.com",
    imageUrl: "",
    color: "Linen Beige",
    material: "Upholstered Linen",
    style: "modern",
  }),
  item({
    name: "Queen Mattress – Medium Firm",
    category: "beds-mattresses",
    subcategory: "Mattresses",
    widthIn: 60,
    depthIn: 80,
    heightIn: 10,
    price: 399,
    vendor: "Zinus",
    vendorUrl: "https://zinus.com",
    imageUrl: "",
    color: "White",
    material: "Memory Foam",
    style: "modern",
  }),
  item({
    name: "King Mattress – Hybrid",
    category: "beds-mattresses",
    subcategory: "Mattresses",
    widthIn: 76,
    depthIn: 80,
    heightIn: 12,
    price: 599,
    vendor: "Nectar",
    vendorUrl: "https://nectarsleep.com",
    imageUrl: "",
    color: "White",
    material: "Hybrid Spring/Foam",
    style: "modern",
  }),
  item({
    name: "Murphy Bed Cabinet – Queen",
    category: "beds-mattresses",
    subcategory: "Murphy Beds",
    widthIn: 66,
    depthIn: 18,
    heightIn: 88,
    price: 1899,
    vendor: "Wilding Wallbeds",
    vendorUrl: "https://wildingwallbeds.com",
    imageUrl: "",
    color: "Espresso",
    material: "Engineered Wood",
    style: "contemporary",
  }),
  item({
    name: "Daybed with Trundle",
    category: "beds-mattresses",
    subcategory: "Daybeds",
    widthIn: 42,
    depthIn: 80,
    heightIn: 36,
    price: 479,
    vendor: "Pottery Barn",
    vendorUrl: "https://potterybarn.com",
    imageUrl: "",
    color: "Antique White",
    material: "Wood",
    style: "farmhouse",
  }),
  item({
    name: "Queen Sleeper Sofa",
    category: "beds-mattresses",
    subcategory: "Sofa Beds",
    widthIn: 84,
    depthIn: 38,
    heightIn: 34,
    price: 1249,
    vendor: "Crate & Barrel",
    vendorUrl: "https://crateandbarrel.com",
    imageUrl: "",
    color: "Charcoal",
    material: "Performance Fabric",
    style: "modern",
  }),

  // ══════════════════════════════════════
  //  SEATING
  // ══════════════════════════════════════
  item({
    name: "L-Shape Sectional Sofa",
    category: "seating",
    subcategory: "Sofas",
    widthIn: 112,
    depthIn: 84,
    heightIn: 34,
    price: 2199,
    vendor: "Article",
    vendorUrl: "https://article.com",
    imageUrl: "",
    color: "Mist Gray",
    material: "Fabric",
    style: "modern",
  }),
  item({
    name: "Mid-Century Loveseat",
    category: "seating",
    subcategory: "Loveseats",
    widthIn: 60,
    depthIn: 34,
    heightIn: 33,
    price: 899,
    vendor: "West Elm",
    vendorUrl: "https://westelm.com",
    imageUrl: "",
    color: "Olive",
    material: "Velvet",
    style: "mid-century",
  }),
  item({
    name: "Accent Armchair",
    category: "seating",
    subcategory: "Accent Chairs",
    widthIn: 30,
    depthIn: 32,
    heightIn: 33,
    price: 449,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "Cream",
    material: "Boucle",
    style: "contemporary",
  }),
  item({
    name: "Woven Rattan Chair",
    category: "seating",
    subcategory: "Accent Chairs",
    widthIn: 28,
    depthIn: 30,
    heightIn: 32,
    price: 349,
    vendor: "World Market",
    vendorUrl: "https://worldmarket.com",
    imageUrl: "",
    color: "Natural",
    material: "Rattan",
    style: "coastal",
  }),
  item({
    name: "Bar Stool (Set of 2)",
    category: "seating",
    subcategory: "Bar Stools",
    widthIn: 18,
    depthIn: 20,
    heightIn: 30,
    price: 249,
    vendor: "Wayfair",
    vendorUrl: "https://wayfair.com",
    imageUrl: "",
    color: "Black/Walnut",
    material: "Metal + Wood",
    style: "industrial",
  }),
  item({
    name: "Dining Chair (Set of 4)",
    category: "seating",
    subcategory: "Dining Chairs",
    widthIn: 20,
    depthIn: 22,
    heightIn: 34,
    price: 399,
    vendor: "IKEA",
    vendorUrl: "https://ikea.com",
    imageUrl: "",
    color: "Oak",
    material: "Solid Oak",
    style: "scandinavian",
  }),

  // ══════════════════════════════════════
  //  TABLES
  // ══════════════════════════════════════
  item({
    name: "Dining Table – Seats 8",
    category: "tables",
    subcategory: "Dining Tables",
    widthIn: 72,
    depthIn: 36,
    heightIn: 30,
    price: 999,
    vendor: "Article",
    vendorUrl: "https://article.com",
    imageUrl: "",
    color: "Natural Oak",
    material: "Solid Oak",
    style: "scandinavian",
  }),
  item({
    name: "Dining Table – Seats 12",
    category: "tables",
    subcategory: "Dining Tables",
    widthIn: 96,
    depthIn: 42,
    heightIn: 30,
    price: 1599,
    vendor: "Restoration Hardware",
    vendorUrl: "https://rh.com",
    imageUrl: "",
    color: "Weathered Brown",
    material: "Reclaimed Wood",
    style: "farmhouse",
  }),
  item({
    name: "Round Coffee Table",
    category: "tables",
    subcategory: "Coffee Tables",
    widthIn: 36,
    depthIn: 36,
    heightIn: 18,
    price: 349,
    vendor: "West Elm",
    vendorUrl: "https://westelm.com",
    imageUrl: "",
    color: "Marble/Gold",
    material: "Marble + Brass",
    style: "modern",
  }),
  item({
    name: "Nightstand",
    category: "tables",
    subcategory: "Nightstands",
    widthIn: 20,
    depthIn: 16,
    heightIn: 24,
    price: 199,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "Walnut",
    material: "Wood",
    style: "mid-century",
  }),
  item({
    name: "Console Table",
    category: "tables",
    subcategory: "Console Tables",
    widthIn: 48,
    depthIn: 14,
    heightIn: 30,
    price: 449,
    vendor: "Pottery Barn",
    vendorUrl: "https://potterybarn.com",
    imageUrl: "",
    color: "Black",
    material: "Metal + Wood",
    style: "industrial",
  }),
  item({
    name: "Side Table",
    category: "tables",
    subcategory: "Side Tables",
    widthIn: 18,
    depthIn: 18,
    heightIn: 22,
    price: 129,
    vendor: "IKEA",
    vendorUrl: "https://ikea.com",
    imageUrl: "",
    color: "White",
    material: "Laminate",
    style: "scandinavian",
  }),

  // ══════════════════════════════════════
  //  STORAGE
  // ══════════════════════════════════════
  item({
    name: "6-Drawer Dresser",
    category: "storage",
    subcategory: "Dressers",
    widthIn: 60,
    depthIn: 18,
    heightIn: 34,
    price: 699,
    vendor: "West Elm",
    vendorUrl: "https://westelm.com",
    imageUrl: "",
    color: "White/Oak",
    material: "Wood",
    style: "mid-century",
  }),
  item({
    name: "Open Shelving Unit",
    category: "storage",
    subcategory: "Shelving",
    widthIn: 36,
    depthIn: 14,
    heightIn: 72,
    price: 299,
    vendor: "IKEA",
    vendorUrl: "https://ikea.com",
    imageUrl: "",
    color: "Birch",
    material: "Birch Veneer",
    style: "scandinavian",
  }),
  item({
    name: "Storage Bench",
    category: "storage",
    subcategory: "Benches",
    widthIn: 44,
    depthIn: 16,
    heightIn: 18,
    price: 249,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "Linen",
    material: "Upholstered",
    style: "contemporary",
  }),
  item({
    name: "Entryway Coat Rack",
    category: "storage",
    subcategory: "Entryway",
    widthIn: 24,
    depthIn: 12,
    heightIn: 72,
    price: 149,
    vendor: "Wayfair",
    vendorUrl: "https://wayfair.com",
    imageUrl: "",
    color: "Matte Black",
    material: "Metal",
    style: "industrial",
  }),

  // ══════════════════════════════════════
  //  LIGHTING
  // ══════════════════════════════════════
  item({
    name: "Pendant Light – Globe",
    category: "lighting",
    subcategory: "Pendants",
    widthIn: 12,
    depthIn: 12,
    heightIn: 14,
    price: 179,
    vendor: "West Elm",
    vendorUrl: "https://westelm.com",
    imageUrl: "",
    color: "Brass/Frosted",
    material: "Glass + Brass",
    style: "modern",
  }),
  item({
    name: "Table Lamp – Ceramic",
    category: "lighting",
    subcategory: "Table Lamps",
    widthIn: 10,
    depthIn: 10,
    heightIn: 22,
    price: 89,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "White/Linen",
    material: "Ceramic",
    style: "coastal",
  }),
  item({
    name: "Floor Lamp – Arc",
    category: "lighting",
    subcategory: "Floor Lamps",
    widthIn: 14,
    depthIn: 14,
    heightIn: 72,
    price: 229,
    vendor: "Article",
    vendorUrl: "https://article.com",
    imageUrl: "",
    color: "Brass",
    material: "Metal",
    style: "mid-century",
  }),
  item({
    name: "String Lights – Outdoor 48ft",
    category: "lighting",
    subcategory: "Outdoor Lighting",
    widthIn: 576,
    depthIn: 1,
    heightIn: 1,
    price: 49,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "Warm White",
    material: "Plastic/LED",
    style: "farmhouse",
  }),

  // ══════════════════════════════════════
  //  DECOR
  // ══════════════════════════════════════
  item({
    name: "Wall Art – Abstract Set of 3",
    category: "decor",
    subcategory: "Wall Art",
    widthIn: 24,
    depthIn: 1,
    heightIn: 36,
    price: 189,
    vendor: "Minted",
    vendorUrl: "https://minted.com",
    imageUrl: "",
    color: "Multicolor",
    material: "Canvas Print",
    style: "modern",
  }),
  item({
    name: "Round Mirror – 30in",
    category: "decor",
    subcategory: "Mirrors",
    widthIn: 30,
    depthIn: 1,
    heightIn: 30,
    price: 199,
    vendor: "West Elm",
    vendorUrl: "https://westelm.com",
    imageUrl: "",
    color: "Gold",
    material: "Metal Frame",
    style: "modern",
  }),
  item({
    name: "Throw Pillows (Set of 4)",
    category: "decor",
    subcategory: "Pillows & Throws",
    widthIn: 18,
    depthIn: 18,
    heightIn: 6,
    price: 89,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "Mixed Neutrals",
    material: "Cotton/Linen Blend",
    style: "transitional",
  }),
  item({
    name: "Faux Plant – Fiddle Leaf Fig",
    category: "decor",
    subcategory: "Plants",
    widthIn: 18,
    depthIn: 18,
    heightIn: 60,
    price: 119,
    vendor: "Pottery Barn",
    vendorUrl: "https://potterybarn.com",
    imageUrl: "",
    color: "Green",
    material: "Faux",
    style: "modern",
  }),
  item({
    name: "Decorative Tray – Wood",
    category: "decor",
    subcategory: "Trays & Bowls",
    widthIn: 18,
    depthIn: 12,
    heightIn: 2,
    price: 39,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "Natural",
    material: "Mango Wood",
    style: "farmhouse",
  }),
  item({
    name: "Woven Basket Set (3pc)",
    category: "decor",
    subcategory: "Baskets",
    widthIn: 16,
    depthIn: 16,
    heightIn: 14,
    price: 59,
    vendor: "World Market",
    vendorUrl: "https://worldmarket.com",
    imageUrl: "",
    color: "Natural/Black",
    material: "Seagrass",
    style: "coastal",
  }),

  // ══════════════════════════════════════
  //  RUGS & TEXTILES
  // ══════════════════════════════════════
  item({
    name: "Area Rug 8x10 – Jute",
    category: "rugs-textiles",
    subcategory: "Area Rugs",
    widthIn: 96,
    depthIn: 120,
    heightIn: 0,
    price: 349,
    vendor: "Rugs USA",
    vendorUrl: "https://rugsusa.com",
    imageUrl: "",
    color: "Natural",
    material: "Jute",
    style: "coastal",
  }),
  item({
    name: "Area Rug 5x7 – Moroccan",
    category: "rugs-textiles",
    subcategory: "Area Rugs",
    widthIn: 60,
    depthIn: 84,
    heightIn: 0,
    price: 249,
    vendor: "Rugs USA",
    vendorUrl: "https://rugsusa.com",
    imageUrl: "",
    color: "Ivory/Black",
    material: "Polypropylene",
    style: "bohemian",
  }),
  item({
    name: "Linen Duvet Cover Set – Queen",
    category: "rugs-textiles",
    subcategory: "Bedding",
    widthIn: 88,
    depthIn: 92,
    heightIn: 0,
    price: 179,
    vendor: "Brooklinen",
    vendorUrl: "https://brooklinen.com",
    imageUrl: "",
    color: "White",
    material: "Linen",
    style: "modern",
  }),
  item({
    name: "Throw Blanket – Chunky Knit",
    category: "rugs-textiles",
    subcategory: "Blankets",
    widthIn: 50,
    depthIn: 60,
    heightIn: 0,
    price: 69,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "Cream",
    material: "Chenille",
    style: "farmhouse",
  }),
  item({
    name: "Blackout Curtains – 84in (Pair)",
    category: "rugs-textiles",
    subcategory: "Curtains",
    widthIn: 104,
    depthIn: 0,
    heightIn: 84,
    price: 49,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "Navy",
    material: "Polyester",
    style: "contemporary",
  }),

  // ══════════════════════════════════════
  //  OUTDOOR
  // ══════════════════════════════════════
  item({
    name: "Outdoor Dining Set – 6 Person",
    category: "outdoor",
    subcategory: "Dining Sets",
    widthIn: 72,
    depthIn: 42,
    heightIn: 30,
    price: 1299,
    vendor: "Wayfair",
    vendorUrl: "https://wayfair.com",
    imageUrl: "",
    color: "Teak",
    material: "Acacia Wood",
    style: "coastal",
  }),
  item({
    name: "Chaise Lounge (Set of 2)",
    category: "outdoor",
    subcategory: "Loungers",
    widthIn: 26,
    depthIn: 78,
    heightIn: 14,
    price: 599,
    vendor: "Wayfair",
    vendorUrl: "https://wayfair.com",
    imageUrl: "",
    color: "Gray",
    material: "Wicker",
    style: "modern",
  }),
  item({
    name: "Fire Pit Table",
    category: "outdoor",
    subcategory: "Fire Pits",
    widthIn: 44,
    depthIn: 44,
    heightIn: 25,
    price: 799,
    vendor: "Home Depot",
    vendorUrl: "https://homedepot.com",
    imageUrl: "",
    color: "Dark Bronze",
    material: "Aluminum + Stone",
    style: "contemporary",
  }),
  item({
    name: "Outdoor Sofa Set – 4pc",
    category: "outdoor",
    subcategory: "Conversation Sets",
    widthIn: 90,
    depthIn: 32,
    heightIn: 28,
    price: 1499,
    vendor: "Article",
    vendorUrl: "https://article.com",
    imageUrl: "",
    color: "Charcoal",
    material: "Wicker + Sunbrella",
    style: "modern",
  }),
  item({
    name: "Hammock with Stand",
    category: "outdoor",
    subcategory: "Hammocks",
    widthIn: 55,
    depthIn: 120,
    heightIn: 48,
    price: 179,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "Navy Stripe",
    material: "Cotton",
    style: "coastal",
  }),

  // ══════════════════════════════════════
  //  KITCHEN & DINING
  // ══════════════════════════════════════
  item({
    name: "Dinnerware Set – 12 Person",
    category: "kitchen-dining",
    subcategory: "Dinnerware",
    widthIn: 12,
    depthIn: 12,
    heightIn: 12,
    price: 199,
    vendor: "Crate & Barrel",
    vendorUrl: "https://crateandbarrel.com",
    imageUrl: "",
    color: "White",
    material: "Stoneware",
    style: "modern",
  }),
  item({
    name: "Flatware Set – 12 Person",
    category: "kitchen-dining",
    subcategory: "Flatware",
    widthIn: 12,
    depthIn: 6,
    heightIn: 4,
    price: 89,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "Gold",
    material: "Stainless Steel",
    style: "modern",
  }),
  item({
    name: "Cookware Set – 10pc",
    category: "kitchen-dining",
    subcategory: "Cookware",
    widthIn: 24,
    depthIn: 14,
    heightIn: 12,
    price: 299,
    vendor: "Caraway",
    vendorUrl: "https://carawayhome.com",
    imageUrl: "",
    color: "Sage",
    material: "Ceramic Non-Stick",
    style: "modern",
  }),
  item({
    name: "Knife Block Set – 14pc",
    category: "kitchen-dining",
    subcategory: "Cutlery",
    widthIn: 8,
    depthIn: 6,
    heightIn: 14,
    price: 149,
    vendor: "Henckels",
    vendorUrl: "https://zwilling.com",
    imageUrl: "",
    color: "Silver/Wood",
    material: "Stainless Steel",
    style: "modern",
  }),

  // ══════════════════════════════════════
  //  BATHROOM
  // ══════════════════════════════════════
  item({
    name: "Towel Set – 8pc",
    category: "bathroom",
    subcategory: "Towels",
    widthIn: 30,
    depthIn: 56,
    heightIn: 0,
    price: 79,
    vendor: "Brooklinen",
    vendorUrl: "https://brooklinen.com",
    imageUrl: "",
    color: "White",
    material: "Turkish Cotton",
    style: "modern",
  }),
  item({
    name: "Shower Curtain – Waffle Weave",
    category: "bathroom",
    subcategory: "Shower Curtains",
    widthIn: 72,
    depthIn: 0,
    heightIn: 72,
    price: 39,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "White",
    material: "Cotton",
    style: "modern",
  }),
  item({
    name: "Bath Mat – Memory Foam",
    category: "bathroom",
    subcategory: "Bath Mats",
    widthIn: 24,
    depthIn: 36,
    heightIn: 1,
    price: 29,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "Gray",
    material: "Memory Foam",
    style: "contemporary",
  }),
  item({
    name: "Soap Dispenser + Tray Set",
    category: "bathroom",
    subcategory: "Accessories",
    widthIn: 8,
    depthIn: 4,
    heightIn: 8,
    price: 35,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "Matte Black",
    material: "Resin",
    style: "modern",
  }),

  // ══════════════════════════════════════
  //  ADDITIONAL BEDS & MATTRESSES
  // ══════════════════════════════════════
  item({
    name: "Queen/Queen Bunk – Coastal White",
    category: "beds-mattresses",
    subcategory: "Bunk Beds",
    widthIn: 65,
    depthIn: 84,
    heightIn: 72,
    price: 1499,
    vendor: "Francis Lofts & Bunks",
    vendorUrl: "https://francisloftsbunks.com",
    imageUrl: "",
    color: "White",
    material: "Solid Hardwood",
    style: "coastal",
  }),
  item({
    name: "Full/Full Bunk Bed",
    category: "beds-mattresses",
    subcategory: "Bunk Beds",
    widthIn: 58,
    depthIn: 78,
    heightIn: 68,
    price: 699,
    vendor: "Wayfair",
    vendorUrl: "https://wayfair.com",
    imageUrl: "",
    color: "Gray",
    material: "Metal",
    style: "industrial",
  }),
  item({
    name: "Queen Platform Bed – Low Profile",
    category: "beds-mattresses",
    subcategory: "Bed Frames",
    widthIn: 64,
    depthIn: 84,
    heightIn: 12,
    price: 349,
    vendor: "Zinus",
    vendorUrl: "https://zinus.com",
    imageUrl: "",
    color: "Natural Wood",
    material: "Solid Pine",
    style: "scandinavian",
  }),
  item({
    name: "King Upholstered Panel Bed",
    category: "beds-mattresses",
    subcategory: "Bed Frames",
    widthIn: 82,
    depthIn: 88,
    heightIn: 52,
    price: 899,
    vendor: "Pottery Barn",
    vendorUrl: "https://potterybarn.com",
    imageUrl: "",
    color: "Oatmeal Linen",
    material: "Upholstered Linen",
    style: "farmhouse",
  }),
  item({
    name: "Twin Mattress – Bunk Compatible",
    category: "beds-mattresses",
    subcategory: "Mattresses",
    widthIn: 38,
    depthIn: 75,
    heightIn: 8,
    price: 199,
    vendor: "Zinus",
    vendorUrl: "https://zinus.com",
    imageUrl: "",
    color: "White",
    material: "Memory Foam",
    style: "modern",
  }),
  item({
    name: "Full Mattress – Medium Firm",
    category: "beds-mattresses",
    subcategory: "Mattresses",
    widthIn: 54,
    depthIn: 75,
    heightIn: 10,
    price: 349,
    vendor: "Nectar",
    vendorUrl: "https://nectarsleep.com",
    imageUrl: "",
    color: "White",
    material: "Hybrid Foam",
    style: "modern",
  }),

  // ══════════════════════════════════════
  //  ADDITIONAL SEATING
  // ══════════════════════════════════════
  item({
    name: "U-Shape Sectional Sofa",
    category: "seating",
    subcategory: "Sofas",
    widthIn: 130,
    depthIn: 100,
    heightIn: 35,
    price: 3299,
    vendor: "Crate & Barrel",
    vendorUrl: "https://crateandbarrel.com",
    imageUrl: "",
    color: "Cream",
    material: "Performance Fabric",
    style: "modern",
  }),
  item({
    name: "Reclining Sofa – Power",
    category: "seating",
    subcategory: "Sofas",
    widthIn: 88,
    depthIn: 40,
    heightIn: 40,
    price: 1899,
    vendor: "La-Z-Boy",
    vendorUrl: "https://la-z-boy.com",
    imageUrl: "",
    color: "Charcoal",
    material: "Leather",
    style: "contemporary",
  }),
  item({
    name: "Outdoor Bar Stool (Set of 2)",
    category: "seating",
    subcategory: "Bar Stools",
    widthIn: 18,
    depthIn: 20,
    heightIn: 30,
    price: 279,
    vendor: "Wayfair",
    vendorUrl: "https://wayfair.com",
    imageUrl: "",
    color: "Teak/White",
    material: "Acacia + Rope",
    style: "coastal",
  }),
  item({
    name: "Bean Bag Chair – Large",
    category: "seating",
    subcategory: "Accent Chairs",
    widthIn: 42,
    depthIn: 42,
    heightIn: 36,
    price: 169,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "Gray",
    material: "Microfiber",
    style: "contemporary",
  }),

  // ══════════════════════════════════════
  //  ADDITIONAL TABLES
  // ══════════════════════════════════════
  item({
    name: "Kitchen Island Cart",
    category: "tables",
    subcategory: "Kitchen Islands",
    widthIn: 48,
    depthIn: 24,
    heightIn: 36,
    price: 449,
    vendor: "IKEA",
    vendorUrl: "https://ikea.com",
    imageUrl: "",
    color: "White/Butcher Block",
    material: "Wood + Steel",
    style: "farmhouse",
  }),
  item({
    name: "Folding Card Table",
    category: "tables",
    subcategory: "Game Tables",
    widthIn: 34,
    depthIn: 34,
    heightIn: 28,
    price: 89,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "Black",
    material: "Steel",
    style: "contemporary",
  }),
  item({
    name: "End Table with USB Charging",
    category: "tables",
    subcategory: "Side Tables",
    widthIn: 20,
    depthIn: 18,
    heightIn: 24,
    price: 159,
    vendor: "West Elm",
    vendorUrl: "https://westelm.com",
    imageUrl: "",
    color: "Walnut",
    material: "Solid Walnut",
    style: "mid-century",
  }),

  // ══════════════════════════════════════
  //  ADDITIONAL DECOR
  // ══════════════════════════════════════
  item({
    name: "Welcome Sign – Personalized",
    category: "decor",
    subcategory: "Wall Art",
    widthIn: 24,
    depthIn: 1,
    heightIn: 18,
    price: 45,
    vendor: "Etsy",
    vendorUrl: "https://etsy.com",
    imageUrl: "",
    color: "Natural/Black",
    material: "Wood",
    style: "farmhouse",
  }),
  item({
    name: "WiFi Password Sign",
    category: "decor",
    subcategory: "Wall Art",
    widthIn: 8,
    depthIn: 1,
    heightIn: 10,
    price: 19,
    vendor: "Etsy",
    vendorUrl: "https://etsy.com",
    imageUrl: "",
    color: "Black/White",
    material: "Acrylic",
    style: "modern",
  }),
  item({
    name: "Candle Set – Soy (3pc)",
    category: "decor",
    subcategory: "Candles",
    widthIn: 4,
    depthIn: 4,
    heightIn: 5,
    price: 42,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "White",
    material: "Soy Wax",
    style: "modern",
  }),
  item({
    name: "Faux Eucalyptus Stems (6pc)",
    category: "decor",
    subcategory: "Plants",
    widthIn: 8,
    depthIn: 8,
    heightIn: 30,
    price: 29,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "Green",
    material: "Faux",
    style: "modern",
  }),
  item({
    name: "Wooden Serving Board",
    category: "decor",
    subcategory: "Trays & Bowls",
    widthIn: 24,
    depthIn: 8,
    heightIn: 1,
    price: 39,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "Acacia",
    material: "Acacia Wood",
    style: "farmhouse",
  }),

  // ══════════════════════════════════════
  //  VACATION RENTAL ESSENTIALS
  // ══════════════════════════════════════
  item({
    name: "Bunk Bed Curtains – Privacy Set",
    category: "rugs-textiles",
    subcategory: "Curtains",
    widthIn: 60,
    depthIn: 0,
    heightIn: 36,
    price: 39,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "Navy",
    material: "Cotton Blend",
    style: "coastal",
  }),
  item({
    name: "Mattress Protector – Queen (Waterproof)",
    category: "beds-mattresses",
    subcategory: "Mattress Protectors",
    widthIn: 60,
    depthIn: 80,
    heightIn: 0,
    price: 35,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "White",
    material: "Terry Cotton",
    style: "modern",
  }),
  item({
    name: "Mattress Protector – King (Waterproof)",
    category: "beds-mattresses",
    subcategory: "Mattress Protectors",
    widthIn: 76,
    depthIn: 80,
    heightIn: 0,
    price: 39,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "White",
    material: "Terry Cotton",
    style: "modern",
  }),
  item({
    name: "Pillow Set – Queen (4pc)",
    category: "rugs-textiles",
    subcategory: "Bedding",
    widthIn: 20,
    depthIn: 28,
    heightIn: 6,
    price: 49,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "White",
    material: "Down Alternative",
    style: "modern",
  }),
  item({
    name: "Sheet Set – Queen (Microfiber)",
    category: "rugs-textiles",
    subcategory: "Bedding",
    widthIn: 60,
    depthIn: 80,
    heightIn: 0,
    price: 39,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "White",
    material: "Microfiber",
    style: "modern",
  }),
  item({
    name: "Hot Tub Towel Rack – Outdoor",
    category: "outdoor",
    subcategory: "Accessories",
    widthIn: 24,
    depthIn: 14,
    heightIn: 50,
    price: 79,
    vendor: "Wayfair",
    vendorUrl: "https://wayfair.com",
    imageUrl: "",
    color: "Teak",
    material: "Acacia Wood",
    style: "coastal",
  }),
  item({
    name: "Smart Lock – Keypad Entry",
    category: "decor",
    subcategory: "Smart Home",
    widthIn: 3,
    depthIn: 3,
    heightIn: 8,
    price: 199,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "Satin Nickel",
    material: "Metal/Plastic",
    style: "modern",
  }),
  item({
    name: "Noise Machine – White Noise",
    category: "decor",
    subcategory: "Smart Home",
    widthIn: 4,
    depthIn: 4,
    heightIn: 4,
    price: 29,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "White",
    material: "Plastic",
    style: "modern",
  }),
  item({
    name: "Game Set – Board Games Collection",
    category: "decor",
    subcategory: "Games",
    widthIn: 16,
    depthIn: 12,
    heightIn: 12,
    price: 89,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "Mixed",
    material: "Mixed",
    style: "contemporary",
  }),
  item({
    name: "Outdoor Games – Yard Set",
    category: "outdoor",
    subcategory: "Games",
    widthIn: 24,
    depthIn: 12,
    heightIn: 12,
    price: 129,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "Wood/Mixed",
    material: "Wood",
    style: "rustic",
  }),
  item({
    name: "Luggage Rack – Folding",
    category: "storage",
    subcategory: "Bedroom Accessories",
    widthIn: 27,
    depthIn: 17,
    heightIn: 20,
    price: 35,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "Black/Chrome",
    material: "Metal",
    style: "contemporary",
  }),
  item({
    name: "Trash Can – Step Open (13 gal)",
    category: "kitchen-dining",
    subcategory: "Kitchen Essentials",
    widthIn: 16,
    depthIn: 12,
    heightIn: 26,
    price: 49,
    vendor: "simplehuman",
    vendorUrl: "https://simplehuman.com",
    imageUrl: "",
    color: "Stainless Steel",
    material: "Steel",
    style: "modern",
  }),
  item({
    name: "Coffee Maker – 12 Cup",
    category: "kitchen-dining",
    subcategory: "Appliances",
    widthIn: 10,
    depthIn: 8,
    heightIn: 14,
    price: 79,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "Stainless/Black",
    material: "Steel/Plastic",
    style: "modern",
  }),
  item({
    name: "Glassware Set – 16pc",
    category: "kitchen-dining",
    subcategory: "Glassware",
    widthIn: 12,
    depthIn: 12,
    heightIn: 8,
    price: 39,
    vendor: "Target",
    vendorUrl: "https://target.com",
    imageUrl: "",
    color: "Clear",
    material: "Glass",
    style: "modern",
  }),
  item({
    name: "Baking Sheet Set – 3pc",
    category: "kitchen-dining",
    subcategory: "Cookware",
    widthIn: 18,
    depthIn: 13,
    heightIn: 2,
    price: 29,
    vendor: "Amazon",
    vendorUrl: "https://amazon.com",
    imageUrl: "",
    color: "Silver",
    material: "Aluminum",
    style: "modern",
  }),
];

// ── Query helpers ──

export function getCategories(): string[] {
  return Array.from(new Set(CATALOG.map((i) => i.category)));
}

export function getSubcategories(category: string): string[] {
  return Array.from(
    new Set(
      CATALOG.filter((i) => i.category === category).map((i) => i.subcategory)
    )
  );
}

export function getStyles(): DesignStyle[] {
  return Array.from(new Set(CATALOG.map((i) => i.style)));
}

export function searchCatalog(query: string): FurnitureItem[] {
  const q = query.toLowerCase();
  return CATALOG.filter(
    (i) =>
      i.name.toLowerCase().includes(q) ||
      i.category.toLowerCase().includes(q) ||
      i.subcategory.toLowerCase().includes(q) ||
      i.vendor.toLowerCase().includes(q) ||
      i.material.toLowerCase().includes(q) ||
      i.style.toLowerCase().includes(q)
  );
}

export function filterCatalog(filters: {
  category?: string;
  subcategory?: string;
  style?: DesignStyle;
  maxPrice?: number;
}): FurnitureItem[] {
  return CATALOG.filter((i) => {
    if (filters.category && i.category !== filters.category) return false;
    if (filters.subcategory && i.subcategory !== filters.subcategory)
      return false;
    if (filters.style && i.style !== filters.style) return false;
    if (filters.maxPrice && i.price > filters.maxPrice) return false;
    return true;
  });
}
